### ISSUE TITLE
Interne Download Manager has been registered with a fake...

### ISSUE THREAD

**Issue by whwu1118** [WindowsAddict/IDM-Activation-Script#10]
version: 6.41 Build 22 (Oct/19/2023) Full
Recently "Interne Download Manager has been registered with a fake..." is always displayed. I am using the official latest version of the installation package

**Comment by Bush2021** [comment]
After I updated Windows 11 23H2 yesterday, I also encountered this problem. I uninstalled and tried activating again several times, and probably got to the point where it locked the registry. I don't know if this Windows update broke something...

@whwu1118 I suggest we go to Discord and give feedback to the author.

**Comment by WindowsAddict** [comment]
@whwu1118 @Bush2021 
Please run IAS script and share a screenshot.

**Comment by whwu1118** [comment]
This was just executed. Sometimes there is a flash back after executing the script

 
![Snipaste_2023-11-06_02-40-05](https://github.com/WindowsAddict/IDM-Activation-Script/assets/98491543/108c4ccf-a70f-4c19-902b-0f3d8f972dd1)

**Comment by whwu1118** [comment]
@WindowsAddict 
This was just executed. Sometimes there is a flash back after executing the script

 
![Snipaste_2023-11-06_02-40-05](https://github.com/WindowsAddict/IDM-Activation-Script/assets/98491543/24ccbc8b-31a9-4811-a74b-905d13cedc25)

**Comment by WindowsAddict** [comment]
@whwu1118 it seems that there are no errors. Let me know if you still have issues.

**Comment by whwu1118** [comment]
@WindowsAddict 
No problem at the moment. I suspect something has been done with the latest version of the idm installation package. I'll get back to you when I have any questions

**Comment by unkn0w7n** [comment]
I am also facing this issue, I get this prompt
![Screenshot 2023-11-24 150620](https://github.com/WindowsAddict/IDM-Activation-Script/assets/51942695/c1850a13-d145-4683-b6b2-cf5b38cbf640)
and it immediately asks to register again.
![Screenshot 2023-11-24 150650](https://github.com/WindowsAddict/IDM-Activation-Script/assets/51942695/606fd27e-f0a3-4455-954c-02bf564725a6)
![image](https://github.com/WindowsAddict/IDM-Activation-Script/assets/51942695/673bdeb9-6009-4fb0-8e09-ed49391f84e0)

running the command again in powershell works, but the fake serial no. is detected and it gets blocked within half an hour or so.

**Comment by WindowsAddict** [comment]
Thanks. I've updated it to 1.0 with these changes.

**Comment by unkn0w7n** [comment]
was testing for 

> @Bush2021 https://download.ru/files/8TbPVlE5 Please run this test file and let me know if it runs fine with you. Share screenshots.

works on the latest idm 👍

**Comment by spidy2356** [comment]
@WindowsAddict lifetime activation method works for me but after a few minutes, it idm get block and pop up appear of fake serial key. i did trial freeze option but, it shows registration panel on start up each time, is it ok???

**Comment by WindowsAddict** [comment]
@spidy2356 run the freeze trial option and read the gray color line at the end.

**Comment by spidy2356** [comment]
@WindowsAddict it says, if idm pop up for register then reinstall idm. 
in my case idm pop up for register on startup only, should I reinstall or it is ok???????

**Comment by spidy2356** [comment]
@WindowsAddict after run trial freeze option again, it got fixed. restart 2 times, not getting pop up now. thanks
