### ISSUE TITLE
Fack Serial Number

### ISSUE THREAD

**Issue by Pandaver** [WindowsAddict/IDM-Activation-Script#12]
Windows 11 22H2
IAS v0.8 (10-Aug-2023)
![截图_20231127094207](https://github.com/WindowsAddict/IDM-Activation-Script/assets/62326552/572eb7c7-9e6c-4e48-a1ea-27e46fb8ca3d)
No matter how many times run activat, this window will pop up after a few minutes.

**Comment by WindowsAddict** [comment]
It will be fixed in next update soon.

**Comment by Pandaver** [comment]
it work, very thanks

**Comment by BernardByte** [comment]
**Great tool.
Thanks @WindowsAddict.**
