### ISSUE TITLE
Windows Malicious Software Removal Tool (MSRT) Removing Actions from Script

### ISSUE THREAD

**Issue by carl125** [WindowsAddict/IDM-Activation-Script#13]
I've encountered an issue where the Windows Malicious Software Removal Tool (MSRT) is removing certain actions performed by a script I use to activate the IDM app. Upon running the MSRT scan, it flagged and removed something that was previously activated by the script.

I would greatly appreciate any insights into why MSRT might be flagging and removing these actions
Thank you for your time and assistance!

**Comment by ave9858** [comment]
What was removed?

**Comment by carl125** [comment]
> What was removed?

I don't have specific logs or details on what was removed by the MSRT scan. However, following the scan, when attempting to access IDM, the application prompted a registration form, like this image
![image](https://github.com/WindowsAddict/IDM-Activation-Script/assets/80618563/a5053cf2-6128-4dd6-8214-0444af8c4141)

**Comment by ave9858** [comment]
Upload "C:\Windows\debug\mrt.log"

**Comment by sevenreeves7vn** [comment]
Reach out to the support team of IDM  and inquire if they are aware of any issues with their software being flagged by security tools. They might have insights or recommendations on how to handle this situation.  You can as well Check if your security software has an option to whitelist specific files or actions. Whitelisting the script can prevent it from being flagged in future scans.
