### ISSUE TITLE
Another solution for Fake Serial Number

### ISSUE THREAD

**Issue by ugurkahriman** [WindowsAddict/IDM-Activation-Script#19]
Greetings! Your solution for the fake serial number error is very clever, but I think I found the main error. The problem is that you always use the same product key when activating. For example, 3 days ago I created a product key using [this](https://github.com/ghost0507/Internet_Download_Manager_Keygen) script and replaced it with the product key in IAS.cmd. Although it's been 3 days and I've done hundreds of downloads, no popups have appeared. I'm not sure but the problem could be using the same product key all the time. A solution could be to add a unique product key generator to the script for each activation. By the way, thanks for creating this script!

**Comment by WindowsAddict** [comment]
Thanks, checking this,

**Comment by showgood163** [comment]
I can confirm that with this version of IAS, the solution provided by @ugurkahriman is working.

https://github.com/WindowsAddict/IDM-Activation-Script/commit/08dbac006c437657ccdc968283ea952f00cd2d90

**Comment by WindowsAddict** [comment]
[IAS_Test.zip](https://github.com/WindowsAddict/IDM-Activation-Script/files/14229199/IAS_Test.zip)
Implemented here, please test and share results.

**Comment by WindowsAddict** [comment]
Try to trigger many downloads (small), like go to Reddit site, do Ctrl + A and right click and download all the selected links.

**Comment by ugurkahriman** [comment]
> > Try to trigger many downloads (small), like go to Reddit site, do Ctrl + A and right click and download all the selected links.
> 
> Bad news :(
> 
> ![image](https://private-user-images.githubusercontent.com/99109969/303838113-bc44bbbb-e2d2-495a-9d34-a3d35f9a4555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NzIyNDcsIm5iZiI6MTcwNzU3MTk0NywicGF0aCI6Ii85OTEwOTk2OS8zMDM4MzgxMTMtYmM0NGJiYmItZTJkMi00OTVhLTlkMzQtYTNkMzVmOWE0NTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDEzMzIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMDRlZDk0YWI4MTlmYjFmYTA5Y2I3OGI0YmEwZjg4MzkwYzYyYTI1YmFjMmVhNTQxODRiZGY5YWJlNzMwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbqH7R8Q9R_qrEGuw4qKZ1v118_2plRM3KXfeEFYUHw)
> 
> Tried many times to download reddit page and ended with that

Can you reset IDM using the script and try again?

**Comment by WindowsAddict** [comment]
@cyberboh Added v2, https://github.com/WindowsAddict/IDM-Activation-Script/issues/19#issuecomment-1936992176 please test that.

**Comment by Dusk-Golem** [comment]
> @cyberboh Added v2, [#19 (comment)](https://github.com/WindowsAddict/IDM-Activation-Script/issues/19#issuecomment-1936992176) please test that.

Thanks for your efforts mate. Unfortunately the nag screen appeared again for V2. What is worst, the nag screen appeared when the script was running so i re-ran the script without resetting but no good. Guess freeze trial will be the way to go forward.

**Comment by ugurkahriman** [comment]
It's really interesting. Today is day 4 and I haven't received any warning.
P.S. I have hundreds of downloads but I am clearing my download history.

![resim](https://github.com/WindowsAddict/IDM-Activation-Script/assets/140934014/83b3cf0f-c83b-4f73-af14-1ca4221a54f2)

**Comment by WindowsAddict** [comment]
I got the popup too, guess they finally patched this trick after many many years. 
Closing this thread here.
