### ISSUE TITLE
pop-up appears now for the life time  30 day trial

### ISSUE THREAD

**Issue by CorpseSlayer** [WindowsAddict/IDM-Activation-Script#20]
i was wondering if this pop-up can be disable at least?
![image_2024-02-10_111623863](https://github.com/WindowsAddict/IDM-Activation-Script/assets/126618918/e41e4e02-f0e3-489e-b68d-997604c53156)
it started appearing after i enable the life time 30 day trial

**Comment by WindowsAddict** [comment]
It will occasionally appear (once in 2-3 days I guess), as it would if you were in actual trial mode. Can't be removed.
