### ISSUE TITLE
possible fake and infected clone of this repository?

### ISSUE THREAD

**Issue by hl2jeep** [WindowsAddict/IDM-Activation-Script#21]
https://github.com/lstprjct/IDM-Activation-Script
this repo has 5.5k stars and seems to be a carbon-copy of this repo, i have not checked for malware presence but i feel like this repo is possibly botted, there are many spelling mistakes and it seems very sketchy

**Comment by sadracc99n** [comment]
it's probably just a fork, WindowsAddict (the creator of this repo) is on the credits list at the repo you linked

**Comment by WindowsAddict** [comment]
IAS tool was hosted on nsaneforums only, At that time the GitHub repo was created by another user, and after that, I created this GitHub repo.
Another repo was already there before, so it has more activity, that's all.
