### ISSUE TITLE
Am I supposed to have Resume & Delete Completed Options?

### ISSUE THREAD

**Issue by andyxo-xo** [WindowsAddict/IDM-Activation-Script#23]
Hi, I did a fresh install of IDM and did your "freeze" script v1.2. But now when I click the "Delete Completed" icon it says "this feature is available in registered version only". Also the Resume icon function is greyed out. Is this normal behavior for the freeze? Or did I do something wrong? I went ahead and reinstalled IDM again on top of the existing IDM installation and then ran the freeze script again but same problem. Thanks...

**Comment by WindowsAddict** [comment]
@andyxo-xo 
For delete all option, you need to select (ctrl + A) and then delete.
Regarding resume, there is no issue, if download is not complete, resume option should be available.

**Comment by andyxo-xo** [comment]
Hi, thanks for your kind reply and yes you are right. I had forgotten to press stop first before trying to resume. May I ask please what other limitations IDM has now with "freeze" besides not being able to quickly click the Delete Completed button?

And is there an uninstall option for your fix (something that will return everything that your script does back to the way it was)? 

Thanks again...

**Comment by WindowsAddict** [comment]
@andyxo-xo there are no other limitations in freeze trial option.
You can use uninstall option in script to reset everything as it was.
