### ISSUE TITLE
IDM keeps showing me "you have 30 days left to activate IDM"

### ISSUE THREAD

**Issue by RealFX-Code** [WindowsAddict/IDM-Activation-Script#25]
as the title suggests, I used the "freeze trial" option in IAS and IDM keeps telling me I have 30 days left at random intervals.

Is this intentional?

**Comment by WindowsAddict** [comment]
@RealFX-Code in normal trial mode, it also sometime may show that 30 days trail period is remaining, that's normal and expected.
