### ISSUE TITLE
How can we disable popup for 30 days remaining 

### ISSUE THREAD

**Issue by bolavefasfas** [WindowsAddict/IDM-Activation-Script#27]
I get annoying popup every day 3-4 times 
about you have 30 days remaining do you want to buy 

I have suucessfuly froze trial just need a way to disable the popup

**Comment by WindowsAddict** [comment]
That popup repetition depends upon how much you are downloading, unfortunately, it can't be disabled easily.

**Comment by bolavefasfas** [comment]
> That popup repetition depends upon how much you are downloading, unfortunately, it can't be disabled easily.

20 files per month approx 

Still if their is a way to disable it you can send link to wiki I can give it a shot
