### ISSUE TITLE
Error message on CMD

### ISSUE THREAD

**Issue by Surufisu** [WindowsAddict/IDM-Activation-Script#28]
I clicked on the IAS.cmd and am getting this error message. Tried running it as admin, still nothing, here's the message that I am getting:

==== ERROR ====

ConstrainedLanguage

PowerShell is not working. Aborting...
If you have applied restrictions on Powershell then undo those changes.

Check this page for help. https://massgrave.dev/idm-activation-script.html#Troubleshoot
Press any key to exit...

![Untitled](https://github.com/WindowsAddict/IDM-Activation-Script/assets/157504529/252462d3-c48a-480c-853d-0cd1348b189d)

**Comment by WindowsAddict** [comment]
@Surufisu 
You have applied restrictions on powershell in your system, remember how did you do that and undo it. 
You can also try to undo that with this powershell command in admin mode

`Set-ItemProperty 'hklm:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' -name "__PSLockdownPolicy" -Value 8`

After that run MAS, it may work.
