### ISSUE TITLE
Unable to connect to the remote server error

### ISSUE THREAD

**Issue by o2rhkzqx** [WindowsAddict/IDM-Activation-Script#6]
Please help me, I am getting below error while executing command `irm https://massgrave.dev/ias | iex`

![image](https://github.com/WindowsAddict/IDM-Activation-Script/assets/104969742/a715773e-4fdb-4675-8d7a-cf808a17ccd5)

**Comment by WindowsAddict** [comment]
The most likely cause of that is DNS. 
Try Fix DNS script, let me know if it still doesn't work
https://massgrave.dev/licensing-servers-issue.html#Fix_DNS

**Comment by WindowsAddict** [comment]
@o2rhkzqx 
Use the latest version 0.9, and let me know if the issue persists.
