### ISSUE TITLE
Very slow in removing the registries

### ISSUE THREAD

**Issue by Nirzak** [WindowsAddict/IDM-Activation-Script#7]
The script is deleting registries for over 2 hours on my PC and still it hasn’t completed yet. It’s taking 4-5 seconds to delete a single registry. That’s making this script really very slow for removing older registries. 

And one more thing Isn’t just removing idm’s registries should be enough! then why does it removing the blank registries?

**Comment by WindowsAddict** [comment]
I need to work on it to make it faster. 
IDM creates some blank registry keys as well and it affects the activation status, that's why the script deletes them.

**Comment by Nirzak** [comment]
> I need to work on it to make it faster. IDM creates some blank registry keys as well and it affects the activation status, that's why the script deletes them.

Oh I see. Thanks for the response! After running for almost 2 hours the script successfully activated my idm and now idm is running fine. Thanks a lot!
