### ISSUE TITLE
Activation nag screen

### ISSUE THREAD

**Issue by tanaduda** [WindowsAddict/IDM-Activation-Script#9]
IDM starts to show activation nag screen. I´ve tried to activate 3 times (reseted activation/trial before too), but the problem persists.

idman641build22f
IDM Activation Script 0.8

**Comment by kendofriendo** [comment]
Doesn't work with latest version. Also, IAS.cmd doesn't run `The input line is too long.
The syntax of the command is incorrect.`

**Comment by WindowsAddict** [comment]
@kendofriendo 
You need to give more details.
- Screenshot of IAS script error
- Have you tried powershell and traditional method both to launch IAS?
